# Generated by Django 6.0.2 on 2026-07-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_update_trackerdata_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='SMART-GUARDIAN-001', max_length=64, unique=True)),
                ('guardian_phone', models.CharField(blank=True, default='', max_length=20)),
                ('geofence_latitude', models.FloatField(default=0.0)),
                ('geofence_longitude', models.FloatField(default=0.0)),
                ('geofence_radius_m', models.FloatField(default=500.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
